### ISSUE TITLE
/run/secrets/kubernetes.io/serviceaccount/ca.crt: No such file or directory

### ISSUE THREAD

**Issue by lenhattan86** [newrelic/k8s-webhook-cert-manager#24] opened 2020-06-30 15:35 UTC
I run the cert gen script on my laptop (Mac OS) and got the following errors:

```
creating certs in tmpdir /var/folders/6b/wmx7z7bs7sx3r7tx_rt9z6cc0000gp/T/tmp.Y6seDAGr 
Generating RSA private key, 2048 bit long modulus
.........+++
..................................+++
e is 65537 (0x10001)
certificatesigningrequest.certificates.k8s.io "k8sbot-webhook-service.k8sbot-system" deleted
WARN: Previous CSR was found and removed.
certificatesigningrequest.certificates.k8s.io/k8sbot-webhook-service.k8sbot-system created
NAME                                   AGE   SIGNERNAME                     REQUESTOR          CONDITION
k8sbot-webhook-service.k8sbot-system   0s    kubernetes.io/legacy-unknown   kubernetes-admin   Pending
certificatesigningrequest.certificates.k8s.io/k8sbot-webhook-service.k8sbot-system approved
secret/k8sbot-webhook-server-cert configured
./webhook_cert_gen.sh: line 166: /run/secrets/kubernetes.io/serviceaccount/ca.crt: No such file or directory
INFO: Trying to patch webhook adding the caBundle.
mutatingwebhookconfiguration.admissionregistration.k8s.io/k8sbot-mutating-webhook-configuration patched (no change)
```

**Comment by lenhattan86** [comment] 2020-06-30 15:55
Do I have to run the script on the master node?

**Comment by douglascamata** [comment] 2020-06-30 15:58
No. But it looks like for some reason K8s is not mounting the cluster CA in your container. This is the root cause of the problem.

**Comment by lenhattan86** [comment] 2020-06-30 16:45
@douglascamata Can you elaborate more? Which container did you mention?
I am using K8s Kind, did anyone experience the same issue?

**Comment by douglascamata** [comment] 2020-06-30 16:57
Can you share the yaml file you're using to run this first, please? The certificates should be mounted automatically if a service account is assigned to the job, which we do assign if you downloaded the YAML file through [the instructions in our documentation](https://docs.newrelic.com/docs/integrations/kubernetes-integration/link-your-applications/link-your-applications-kubernetes#configure-injection). 

Also, I never tested in kind... maybe it could require some additional configuration. I use minikube and it works out of the box.

**Comment by lenhattan86** [comment] 2020-06-30 17:09
Wait~~ I just ran that script directly on my laptop without following any instructions. Let me try it out again.

**Comment by paologallinaharbur** [comment] 2020-10-19 12:58
I'll mark it as solved

**Closed by paologallinaharbur** 2020-10-19 12:58 UTC
